dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
notifications:
  email:
    recipients:
      -josemamup@gmail.com
    on_success: never
    on_failure: never
before_script:
- cp decide/local_settings.travis.py decide/local_settings.py
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp local_settings.travis.py local_settings.py
- python ./manage.py test --keepdb

